### ISSUE TITLE
last *:playUpdateSecret wirft einen Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-web#16]
```
[AmiKoWeb] $ last *:playUpdateSecret
[info] Updating application secret in /usr/local/src/amiko-web/conf/application.conf
com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${?APPLICATION_SECRET})
	at com.typesafe.config.impl.ConfigReference.notResolved(ConfigReference.java:33)
	at com.typesafe.config.impl.ConfigReference.valueType(ConfigReference.java:40)
	at com.typesafe.config.impl.SimpleConfig.hasPath(SimpleConfig.java:96)
	at play.sbt.ApplicationSecretGenerator$$anonfun$updateSecretTask$1.apply(ApplicationSecretGenerator.scala:47)
	at play.sbt.ApplicationSecretGenerator$$anonfun$updateSecretTask$1.apply(ApplicationSecretGenerator.scala:31)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:playUpdateSecret) com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${?APPLICATION_SECRET})

**Comment by zdavatz** [comment]
solved with: https://github.com/playframework/playframework/issues/6411
