### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-web#2]
When running _activator_ you may run into this node/npm error:
```
[error] ReferenceError: internalBinding is not defined
[error]     at evalmachine.<anonymous>:25:1
[error]     at Object.<anonymous> (/home/zeno/.software/amiko-web/project/target/node-modules/webjars/npm/node_modules/graceful-fs/fs.js:11:1)
[error]     at Module._compile (internal/modules/cjs/loader.js:799:30)
[error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
[error]     at Module.load (internal/modules/cjs/loader.js:666:32)
[error]     at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
[error]     at Function.Module._load (internal/modules/cjs/loader.js:598:3)
[error]     at Module.require (internal/modules/cjs/loader.js:705:19)
[error]     at require (internal/modules/cjs/helpers.js:14:16)
[error]     at Object.<anonymous> (/home/zeno/.software/amiko-web/project/target/node-modules/webjars/npm/node_modules/graceful-fs/graceful-fs.js:3:27)
```
this error may also pop-up:
`Cannot find module 'internal/fs'`

Install 
* node v6.9.5
* npm v3.10.10

also see https://github.com/npm/npm/issues/14232 for Reference.

**Comment by zdavatz** [comment]
This is the solution: https://github.com/zdavatz/amiko-web#install-nodejs-with-nvm
