### ISSUE TITLE
FTS search for AmiKo-Web not longer works after Drugshortage update.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-web#29]
1. FTS search result for "swisspeddose" throws an error if you click on "swisspeddose". The same search works on iOS.
2. Same problem with FTS search for "SAPP" or "sappinfo".
3. Also see: https://github.com/zdavatz/fachinfo_ai/issues/9
4. The AmiKo-Web error is:
```
@400000005ffffdf13253bc54 ! @7idjig9ko - Internal server error, for (GET) [/de/fulltext?id=92d38dedd8&key=Swisspeddose] ->
@400000005ffffdf13253c03c  
@400000005ffffdf13253c03c play.api.UnexpectedException: Unexpected exception[NumberFormatException: For input string: "18-7680623550033"]
@400000005ffffdf13253c424       at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:276)
@400000005ffffdf13253c80c       at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
@400000005ffffdf132545c7c       at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
@400000005ffffdf132546064       at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
@400000005ffffdf13254644c       at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
@400000005ffffdf132546834       at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
@400000005ffffdf1325477d4       at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
@400000005ffffdf132547bbc       at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
@400000005ffffdf132547fa4       at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
@400000005ffffdf13254a6b4       at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
@400000005ffffdf13254aa9c Caused by: java.lang.NumberFormatException: For input string: "18-7680623550033"
@400000005ffffdf13254ae84       at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
@400000005ffffdf13254b26c       at java.lang.Integer.parseInt(Integer.java:580)
@400000005ffffdf13254b26c       at java.lang.Integer.parseInt(Integer.java:615)
@400000005ffffdf13254be24       at models.Article.index_to_titles_map(Article.java:196)
@400000005ffffdf13254c20c       at models.FullTextSearch.updateHtml(FullTextSearch.java:93)
@400000005ffffdf13254c20c       at controllers.MainController.showFullTextSearchResult(MainController.java:273)
@400000005ffffdf13254c5f4       at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$18$$anonfun$apply$18.apply(Routes.scala:593)
@400000005ffffdf13254c9dc       at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$18$$anonfun$apply$18.apply(Routes.scala:593)
@400000005ffffdf13254d97c       at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
@400000005ffffdf13254dd64       at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
```

**Comment by zdavatz** [comment]
Why do we have an input string of `18-7680623550033` with "18-"? This is strange. "7680623550033" ist the GTIN of Acetalgin, the first Drugshortage product.
