### ISSUE TITLE
Ajax Error - Unexpected exception[NullPointerException: null]

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-web#37]
Add Ponstan and Marcoumar to the Interaction basket:
```
2021-05-03 14:27:31.790667500 ! @7ji7g28of - Internal server error, for (GET) [/de/interactions/7680459860719,7680193950141,7680307850299,66231,66495,49999,62451,62892,63025,65643,62630,62556,40467,61865,55465,53342,56976,57664,66152,45204,65330,21037,66422,45465,56120,60916,55172,57851,58325,50203,,66231,66495,49999,62451,62892,63025,65643,62630,62556,40467,61865,53342,56976,57664,66152,45204,65330,21037,66422,45465,56120,60916,55172,57851,58325,50203,] ->
2021-05-03 14:27:31.790682500
2021-05-03 14:27:31.790682500 play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
2021-05-03 14:27:31.790686500 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:276)
2021-05-03 14:27:31.790686500 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
2021-05-03 14:27:31.790687500 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
2021-05-03 14:27:31.790687500 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
2021-05-03 14:27:31.790689500 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
2021-05-03 14:27:31.790689500 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
2021-05-03 14:27:31.790696500 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
2021-05-03 14:27:31.790696500 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
2021-05-03 14:27:31.790697500 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
2021-05-03 14:27:31.790697500 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
2021-05-03 14:27:31.790699500 Caused by: java.lang.NullPointerException: null
2021-05-03 14:27:31.790699500 	at models.InteractionsData.updateHtml(InteractionsData.java:199)
2021-05-03 14:27:31.790700500 	at controllers.MainController.interactionsBasket(MainController.java:247)
2021-05-03 14:27:31.790700500 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$9$$anonfun$apply$9.apply(Routes.scala:539)
2021-05-03 14:27:31.790701500 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$9$$anonfun$apply$9.apply(Routes.scala:539)
2021-05-03 14:27:31.790702500 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
2021-05-03 14:27:31.790703500 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
2021-05-03 14:27:31.790703500 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
2021-05-03 14:27:31.790708500 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
2021-05-03 14:27:31.790709500 	at actions.MyActionCreator$1.call(MyActionCreator.java:27)
2021-05-03 14:27:31.790709500 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
2021-05-03 14:27:35.891066500 [error] application -
2021-05-03 14:27:35.891068500
2021-05-03 14:27:35.891068500 ! @7ji7g2f07 - Internal server error, for (GET) [/de/interactions/7680459860719,7680193950141,7680307850299,66231,66495,49999,62451,62892,63025,65643,62630,62556,40467,61865,55465,53342,56976,57664,66152,45204,65330,21037,66422,45465,56120,60916,55172,57851,58325,50203,,66231,66495,49999,62451,62892,63025,65643,62630,62556,40467,61865,53342,56976,57664,66152,45204,65330,21037,66422,45465,56120,60916,55172,57851,58325,50203,] ->
2021-05-03 14:27:35.891084500
2021-05-03 14:27:35.891084500 play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
2021-05-03 14:27:35.891087500 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:276)
2021-05-03 14:27:35.891087500 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
2021-05-03 14:27:35.891088500 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
2021-05-03 14:27:35.891089500 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
2021-05-03 14:27:35.891091500 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
2021-05-03 14:27:35.891092500 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
2021-05-03 14:27:35.891123500 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
2021-05-03 14:27:35.891124500 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
2021-05-03 14:27:35.891125500 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
2021-05-03 14:27:35.891125500 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
2021-05-03 14:27:35.891128500 Caused by: java.lang.NullPointerException: null
2021-05-03 14:27:35.891129500 	at models.InteractionsData.updateHtml(InteractionsData.java:199)
2021-05-03 14:27:35.891129500 	at controllers.MainController.interactionsBasket(MainController.java:247)
2021-05-03 14:27:35.891130500 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$9$$anonfun$apply$9.apply(Routes.scala:539)
2021-05-03 14:27:35.891131500 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$9$$anonfun$apply$9.apply(Routes.scala:539)
2021-05-03 14:27:35.891133500 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157)
2021-05-03 14:27:35.891134500 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:156)
2021-05-03 14:27:35.891134500 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
2021-05-03 14:27:35.891141500 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
2021-05-03 14:27:35.891142500 	at actions.MyActionCreator$1.call(MyActionCreator.java:27)
2021-05-03 14:27:35.891143500 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
```

**Comment by b123400** [comment]
I cannot reproduce the issue, do you have these files?
- `sqlite/drug_interactions_csv_de.csv`
- `sqlite/drug_interactions_csv_fr.csv`

**Comment by zdavatz** [comment]
Thanks! Strange, `drug_interactions_csv_de.csv` was missing!
