### ISSUE TITLE
starting App with `-Dadswiss_test=true`

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko-web#92]
1. Starting the App with: `-Dadswiss_test=true`
2. Results in: 
```
@40000000669cf33710c0528c Caused by: com.typesafe.config.ConfigException$WrongType: system properties: feature.prescriptions has type STRING rather than BOOLEAN
@40000000669cf33710c0528c 	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:164)
@40000000669cf33710c05674 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:175)
@40000000669cf33710c1d92c 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:181)
@40000000669cf33710c1dd14 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
@40000000669cf33710c1dd14 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
@40000000669cf33710c1dd14 	at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:219)
@40000000669cf33710c1fc54 	at controllers.MainController.getShowPrescriptions(MainController.java:105)
@40000000669cf33710c35be4 	at controllers.MainController.getViewContext(MainController.java:115)
@40000000669cf33710c35be4 	at controllers.MainController.index(MainController.java:131)
@40000000669cf33710c35be4 	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$3(Routes.scala:779)
```

**Comment by zdavatz** [comment]
Typo.
